funcoes_organizadas = {
    # Grupo 1: Funções de download (baixar dados processuais)
    'baixar': [
        'baixar_publicacoes_dje',
        'baixar_acordaos',
        'baixar_cjpg',
        'baixar_municipios',
        'tjsp_baixar_cpopg',
        'tjsp_baixar_cposg',
        'tjsp_baixar_cjpg',
        'tjsp_baixar_cjsg',
        'tjsp_baixar_inicial',
        'tjsp_baixar_intimacoes',
        'tjsp_baixar_tabela_cd_processo',
        'tjsp_baixar_tabela_cpopg_docs',
        'tjsp_baixar_acordaos_cposg',
        'tjsp_baixar_acordaos_cposg2',
        'tjsp_baixar_acordaos_cjsg',
        'tjsp_baixar_cpopg_cd_processo',
        'tjsp_baixar_cjpg_processo',
        'tjsp_baixar_doc_movimentacao'
    ],
    
    # Grupo 2: Funções de leitura (processar HTMLs)
    'ler': [
        'ler_cjsg',
        'ler_acordaos',
        'ler_decisoes',
        'ler_decisoes_monocraticas',
        'ler_decisoes_cposg',
        'ler_despacho',
        'ler_entrada',
        'ler_municipios',
        'tjsp_ler_partes',
        'tjsp_ler_documentos',
        'tjsp_ler_movimentacao',
        'tjsp_ler_cjpg',
        'tjsp_ler_cjsg',
        'tjsp_ler_dados_cpopg',
        'tjsp_ler_dados_cposg',
        'tjsp_ler_intimacoes',
        'tjsp_ler_peticoes',
        'tjsp_ler_sentencas_cjpg',
        'tjsp_ler_tabela_docs',
        'tjsp_ler_historico_classes',
        'mni_ler_partes',
        'mni_ler_dados_basicos'
    ],
    
    # Grupo 3: Funções auxiliares (transformação e apoio)
    'auxiliares': [
        'tjsp_autenticar',
        'tjsp_corrigir_varas',
        'tjsp_classificar_sentenca',
        'tjsp_classificar_recurso',
        'tjsp_classificar_writ',
        'tjsp_parsear_distribuicao',
        'tjsp_gerar_cd_processo',
        'tjsp_varas',
        'tjsp_votacao',
        'pontuar_cnj',
        'remover_assinatura',
        'remover_acentos',
        'cnj_sequencial',
        'numero',
        'ordenar_camaras',
        'ajustar_assuntos',
        'fuzzy_search',
        'rm_duplicados',
        'verificar_datas',
        'latlong_comarca',
        'expr',
        'enquo',
        'enquos',
        'sym',
        'syms',
        'as_name',
        'as_label',
        '%>%',
        ':=',
        '.data',
        'cjpg_table',
        'ggdecisao',
        'lapso'
    ]
}